### PR TITLE
Remove memory leak in Task.

### LINKED ISSUE #71: Memory issue in node application
Hey guys,

I'm using this library v0.3.1 in a node v6.9.5 application. Actually the application runs inside docker container but I'm able to reproduce the problem with following script. The script is
```javascript
'use strict';

const googleMapsClient = require('@google/maps').createClient({
  key: '...'
});

setInterval(() => {
  googleMapsClient.geocode({
    address: '1600 Amphitheatre Parkway, Mountain View, CA'
  }, function(err, response) {
    if (!err) {
      console.log(response.json.results[0].formatted_address);
    }
  });
}, 2000);
```
and I see memory increasing as every new address gets geocoded. Is it supposed to increase like this or am I doing something in a wrong way? Memory heap snapshots are here [Heap.zip](https://github.com/googlemaps/google-maps-services-js/files/811680/Heap.zip)

### PR DESCRIPTION
**Pull request by stephenfarrar**
Fixes #71

### CODE REVIEW

**Comment by kilpa** [comment]
This change breaks the following code example:
`'use strict';
const googleMapsClient = require('@google/maps').createClient({
		key: 'YOUR API TOKEN'
	});

setInterval(() => {
	googleMapsClient.geocode({
		address: '1600 Amphitheatre Parkway, Mountain View, CA'
	}, function(err, response) {
		console.log(err, response.json.results[0].formatted_address);
	});
}, 150);
`

**Comment by priidikvaikla** [comment]
Changing this fix like this https://github.com/priidikvaikla/google-maps-services-js/commit/658b32ffda71ea9757bcf471fc38fb3da4d3cd24 would get it working for me again. But still I see slight increase in memory consumption.

**Comment by stephenfarrar** [comment]
Yes, thanks, you're right that my PR is wrong.

I still haven't got to the bottom of this though. It's still leaking memory, and it looks like maybe a problem in a different place.

**Comment by jvswatson** [comment]
I was just wondering when we might see a patch bump to this library that will include this change? Thanks for all the hard work!

**Comment by kimmobrunfeldt** [comment]
Awesome work! :+1: We are also eagerly waiting for a new release :)

**Pull request merged**
