### PR TITLE
Add region parameter to Text Search API

### PR DESCRIPTION
**Pull request by antonio0**
With this change client.places() can accept the region parameter.

### CODE REVIEW

**Comment by antonio0** [comment]
I signed it!

**Comment by TarekDeeb** [comment]
Any ETA on when this will be merged?

**Comment by antonio0** [comment]
I'm assuming it has gone unnoticed? @stephenmcd 

The region is a supported parameter and as of now it doesn't work with this client  https://developers.google.com/places/web-service/search#TextSearchRequests

**Comment by signorekai** [comment]
Any ETA with this PR?

**Comment by stephenmcd** [comment]
> Any ETA with this PR?

ASAP :-)

**Comment by stephenmcd** [comment]
Thanks Antonio, sorry about the delay.

**Comment by Jekiwijaya** [comment]
Sorry. Newbie here. 

when this feature published in npm?

**Comment by stephenmcd** [comment]
I'm unable to publish a new version right now unfortunately. I've opened an issue with npm here:

https://github.com/npm/npm/issues/20098

Once that's resolved I'll push the new version.

**Comment by stephenmcd** [comment]
New version is on npm now.

**Pull request merged**
