### PR TITLE
added https proxy agent for pursuing the requests behind corporate proxy

### PR DESCRIPTION
**Pull request by amithbs1**
Implemented https-proxy-agent library that connects to an intermediary "proxy" server and issues the CONNECT HTTP method, which tells the proxy to open a direct TCP connection to the destination server. This will help us to get the google maps client api to work from behind the corporate proxies.

### CODE REVIEW

**Comment by amithbs1** [comment]
Is there anything wrong with the Pull request? Can someone review it?

**Comment by amuramoto** [comment]
Should there be a conditional so that proxy is only added to requestOptions if it's actually set?

**Comment by amithbs1** [comment]
@amuramoto I have added the necessary check, as suggested by you.

**Comment by amuramoto** [comment]
Thanks for the PR!

**Pull request merged**
