### PR TITLE
Added error handling for unparseable JSON responses

### PR DESCRIPTION
**Pull request by andrew-stirling**
Added more graceful handling for JSON parse errors (from, e.g., interrupted connection or out-of-memory).

### CODE REVIEW

**Comment by stephenmcd** [comment]
Good idea. Would be slightly better to store the parsed JSON in a variable, and just wrap that assignment in the try/catch, do you want to make that change? Either way, please sign the CLA and I'll merge this.

Thanks!

**Comment by andrew-stirling** [comment]
Updated with isolated try-catch, but currently I have it return immediately after reporting the error. Not sure what your conventions are with returns in the middle of functions (I find it more readable, but this is a point on which reasonable people disagree).

Waiting on a director to sign off on the change since work was done on company time; should be through by Monday.

**Comment by stephenmcd** [comment]
Looks good, thanks a lot!

**Comment by stephenmcd** [comment]
@andrew-stirling - still waiting on CLA to merge this, otherwise I'll have to close it.

**Comment by stephenmcd** [comment]
Closing this since it now conflicts and doesn't look like we'll get a CLA.

**Pull request closed without merging**
