### PR TITLE
Fixed handling multibyte encoding responses

### PR DESCRIPTION
**Pull request by glintik**
Hi!

I see an issue with wrong HTTPS response chunks concatenation with multibyte strings in this code:
`
      var data = '';
      response.on('data', function(chunk) {
        data += chunk;
      });
`
Please consider to review my pull request, fixing this issue.

### CODE REVIEW

**Comment by stephenmcd** [comment]
Thanks a lot. Do you think there's a test we can add as well?

**Comment by glintik** [comment]
IMHO, no test is required in this case.
Thank you for quick response.

**Comment by stephenmcd** [comment]
Well at the very least, it will assist in verifying the fix, and more importantly it will ensure that this always remains working, does that sound worthwhile?

**Comment by glintik** [comment]
Sure, but:
1) I verified the fix before posting it on a few hundreds real requests to Google Maps.
2) Sorry, I can not to offer a simple test to cover a real world case. Issue depends on system networks buffers and appeared in about 5% of my requests on my OS X.

**Comment by stephenmcd** [comment]
Sorry if it was unclear, I meant it would help the person reviewing this (me) to verify the fix is correct. 

Can you at least provide some more detail around the types of requests you were making to cause the issue? I hope you can appreciate I need to reproduce the issue before I can merge this.

**Comment by glintik** [comment]
I selected 6 geocoded addresses, that's broken in most cases and wrote this 
[jasmine test](https://github.com/glintik/google-maps-services-js/commit/142a492482458d6439efa7012d457b2c9e1e741b). Hope this helps.

**Comment by stephenmcd** [comment]
That's a huge help! Thanks a lot.

**Pull request merged**
