### PR TITLE
Added example of promise constructor

### PR DESCRIPTION
**Pull request by G-Rath**
Addresses #99 

I opted not to use ES6 shorthand here, as I think it's nicer to make clear that the property name is 'Promise'.

If it's not clear enough, I'm happy to also add an example of using Bluebird or another Promise library.

### CODE REVIEW

**Comment by G-Rath** [comment]
I signed it!

**Comment by stephenmcd** [comment]
That's great, thanks a lot!

**Comment by pcooney10** [comment]
Hey, this is great @G-Rath. 

@stephenmcd I'm not sure how you manage the source/build for the [gh-pages](https://googlemaps.github.io/google-maps-services-js/docs/) site, but it would've been helpful to have this example on there too.

**Comment by stephenmcd** [comment]
@pcooney10 I've just updated the docs site

**Pull request merged**
